### PR TITLE
update java and gradle.

### PR DESCRIPTION
**Pull request by y0av**
i didn't check the example only that the package now works with new gradle and android studio 2024.2.1 target SDK 34

### CODE REVIEW

**Review by quang305 — APPROVED** [review]

**Comment by mfurkanyuceal** [comment]
I tried to get the debug build but I got the following error.
Flutter version: 3.29.3
Gradle version: 8.10.1

`
/Users/muhammedfurkanyuceal/.pub-cache/git/bluetooth_enable_fork-63caf2c41f714fc35ba5a3369047ea8b90c0dbd3/android/src/main/java/com/hui/bluetooth_enable/BluetoothEnablePlugin.java:21: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/muhammedfurkanyuceal/.pub-cache/git/bluetooth_enable_fork-63caf2c41f714fc35ba5a3369047ea8b90c0dbd3/android/src/main/java/com/hui/bluetooth_enable/BluetoothEnablePlugin.java:29: error: cannot find symbol
    private Registrar registrar;
            ^
  symbol:   class Registrar
  location: class BluetoothEnablePlugin
/Users/muhammedfurkanyuceal/.pub-cache/git/bluetooth_enable_fork-63caf2c41f714fc35ba5a3369047ea8b90c0dbd3/android/src/main/java/com/hui/bluetooth_enable/BluetoothEnablePlugin.java:40: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class BluetoothEnablePlugin
/Users/muhammedfurkanyuceal/.pub-cache/git/bluetooth_enable_fork-63caf2c41f714fc35ba5a3369047ea8b90c0dbd3/android/src/main/java/com/hui/bluetooth_enable/BluetoothEnablePlugin.java:46: error: cannot find symbol
    BluetoothEnablePlugin(Registrar r) {
                          ^
  symbol:   class Registrar
  location: class BluetoothEnablePlugin
Note: /Users/muhammedfurkanyuceal/.pub-cache/git/bluetooth_enable_fork-63caf2c41f714fc35ba5a3369047ea8b90c0dbd3/android/src/main/java/com/hui/bluetooth_enable/BluetoothEnablePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.


`

**Comment by y0av** [comment]
@mfurkanyuceal  I actually know this error. if im not mistaken thats because of Deprecated imperative apply of Flutter's Gradle plugins which are deprecated since flutter version 3.16 so either downgrade Flutter to > 3 and < 3.16 or [Migrate like so](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) (thats actually not hard at all just follow this guide step by step). if you do so maybe contribute a commit here as well.

**Comment by Alystrasz** [comment]
To ease up things, I ended up updating all Java, Gradle and Flutter plugin versions at the same time in d28899c22c3b66766a2bc096dd50b8bce4234017.
Thanks for your contribution anyway!
